import { Inter, Karma } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const karma = Karma({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karma.className}>{children}</body>
    </html>
  );
}
